version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - DB_NAME=task2
      - DB_USER=postgres
      - DB_PASSWORD=2004
      - DB_HOST=db
      - JWT_SECRET=cvhvbjbnkjnk
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: task2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004
    ports:
      - '5432:5432'
    volumes:
      - /Users/xllsc/OneDrive/Desktop/pgdata:/data/db

volumes:
  pgdata:
